### ISSUE TITLE
valueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6,) + inhomogeneous part.

### ISSUE THREAD

**Issue by beautymama** [Robust-Jay/SSD-Resnet-Attention-FeatureFusion#12]
Traceback (most recent call last):
  File "/home/s/SSD-Resnet-Attention-FeatureFusion-master/train.py", line 117, in <module>
    main()
  File "/home/s/SSD-Resnet-Attention-FeatureFusion-master/train.py", line 108, in main
    model = train(cfg, args)
  File "/home/s/SSD-Resnet-Attention-FeatureFusion-master/train.py", line 47, in train
    model = do_train(cfg, model, train_loader, optimizer, scheduler, checkpointer, device, arguments, args)
  File "/home/s/SSD-Resnet-Attention-FeatureFusion-master/ssd/engine/trainer.py", line 74, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "/home/s/.conda/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/s/.conda/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/s/.conda/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/s/.conda/envs/pytorch/lib/python3.9/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/s/.conda/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/s/.conda/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/s/.conda/envs/pytorch/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/s/SSD-Resnet-Attention-FeatureFusion-master/ssd/data/datasets/voc.py", line 37, in __getitem__
    image, boxes, labels = self.transform(image, boxes, labels)
  File "/home/s/SSD-Resnet-Attention-FeatureFusion-master/ssd/data/transforms/transforms.py", line 75, in __call__
    img, boxes, labels = t(img, boxes, labels)
  File "/home/s/SSD-Resnet-Attention-FeatureFusion-master/ssd/data/transforms/transforms.py", line 273, in __call__
    mode = random.choice(self.sample_options)
  File "mtrand.pyx", line 920, in numpy.random.mtrand.RandomState.choice
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6,) + inhomogeneous part.
I put the voc2007 under VOC_ROOT, and export, but it can not run ,Please help me! Thank you!

**Comment by JYChoi20** [comment]
did u solve this problem? I also meet this, still cannot solve.

**Comment by beautymama** [comment]
Maybe your dataset had problems, or your environments



---Original---
From: ***@***.***&gt;
Date: Thu, Jun 15, 2023 18:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Robust-Jay/SSD-Resnet-Attention-FeatureFusion] valueError:setting an array element with a sequence. The requested array has aninhomogeneous shape after 1 dimensions. The detected shape was (6,) +inhomogeneous part. (Issue #12)




 
did u solve this problem? I also meet this, still cannot solve.
