### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6,) + inhomogeneous part.

### ISSUE THREAD

**Issue by JYChoi20** [Robust-Jay/SSD-Resnet-Attention-FeatureFusion#13]
Traceback (most recent call last):
  File "D:\Desktop\SSD-Resnet-Attention-FeatureFusion-master\train.py", line 117, in <module>
    main()
  File "D:\Desktop\SSD-Resnet-Attention-FeatureFusion-master\train.py", line 108, in main
    model = train(cfg, args)
  File "D:\Desktop\SSD-Resnet-Attention-FeatureFusion-master\train.py", line 47, in train
    model = do_train(cfg, model, train_loader, optimizer, scheduler, checkpointer, device, arguments, args)
  File "D:\Desktop\SSD-Resnet-Attention-FeatureFusion-master\ssd\engine\trainer.py", line 74, in do_train
    for iteration, (images, targets, _) in enumerate(data_loader, start_iter):
  File "D:\Desktop\New folder\SSD-Resnet-Attention-FeatureFusion-master\lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__   
    data = self._next_data()
  File "D:\Desktop\New folder\SSD-Resnet-Attention-FeatureFusion-master\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "D:\Desktop\New folder\SSD-Resnet-Attention-FeatureFusion-master\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "D:\Desktop\New folder\SSD-Resnet-Attention-FeatureFusion-master\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "D:\Desktop\New folder\SSD-Resnet-Attention-FeatureFusion-master\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Desktop\New folder\SSD-Resnet-Attention-FeatureFusion-master\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch     
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Desktop\New folder\SSD-Resnet-Attention-FeatureFusion-master\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Desktop\New folder\SSD-Resnet-Attention-FeatureFusion-master\lib\site-packages\torch\utils\data\dataset.py", line 243, in __getitem__   
    return self.datasets[dataset_idx][sample_idx]
  File "D:\Desktop\SSD-Resnet-Attention-FeatureFusion-master\ssd\data\datasets\voc.py", line 42, in __getitem__
    image, boxes, labels = self.transform(image, boxes, labels)
  File "D:\Desktop\SSD-Resnet-Attention-FeatureFusion-master\ssd\data\transforms\transforms.py", line 75, in __call__
    img, boxes, labels = t(img, boxes, labels)
  File "D:\Desktop\SSD-Resnet-Attention-FeatureFusion-master\ssd\data\transforms\transforms.py", line 274, in __call__
    mode = random.choice(self.sample_options)
  File "mtrand.pyx", line 920, in numpy.random.mtrand.RandomState.choice
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6,) + inhomogeneous part.
请问这是什么原因报错

**Comment by Joy2Boy** [comment]
请问你解决了吗？
